openapi: 3.0.0
info:
  title: TCP/IP Client API
  version: 1.0.0
paths:
  /api/send:
    post:
      summary: Send a message to a TCP client
      parameters:
        - name: msg
          in: query
          required: true
          schema:
            type: string
        - name: clientName
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: string
