apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tcp-ip-api
  description: API for sending messages via TCP/IP microservice
  tags:
    - tcp
    - spring-boot
    - reactive
spec:
  type: openapi
  lifecycle: experimental
  owner: user:aniket
  definition:
    $text: |
      openapi: 3.0.0
      info:
        title: TCP/IP Client API
        version: 1.0.0
      paths:
        /api/send:
          post:
            summary: Send a TCP message
            parameters:
              - in: query
                name: msg
                required: true
                schema:
                  type: string
              - in: query
                name: clientName
                required: true
                schema:
                  type: string
            responses:
              '200':
                description: Successful send and response
