apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tcp-ip-api
  description: API for TCP/IP communication service
  tags:
    - tcp
    - spring-boot
spec:
  type: openapi
  lifecycle: experimental
  owner: user:aniket
  definition:
    $text: ./openapi.yaml
